version: '2'
volumes:
  schema:
  qgis-settings:

services:
  qgis:
    image: qgis/qgis:release-3_28
    volumes:
      - ${PWD}:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - qgis-settings:/root/.local/share/QGIS/QGIS3/profiles/default
      - ./QGIS3.ini:/QGIS3.ini
      - ./qgis_entry.sh:/qgis_entry.sh
      - ./pg_service.conf:/pg_service.conf
    environment:
      - PYTHONPATH=/app:/usr/share/qgis/python/plugins/
      - QGIS_DEBUG=0
      - QGIS_LOG_FILE=/dev/null
      - QGIS_PLUGINPATH=/app
      - DISPLAY=${DISPLAY}
      - PGSERVICEFILE=/pg_service.conf
    entrypoint: "/qgis_entry.sh"
    command:
      - qgis
      - /app/relation.qgs

  db:
    image: camptocamp/postgres:14-postgis-3
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password

  schemaspy:
    image: schemaspy/schemaspy:latest
    environment:
      - DATABASE_TYPE=pgsql
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
    #   --link postgres
    entrypoint:
      - sh
    command:
      - /usr/local/bin/schemaspy
      - '-t'
      - pgsql11
      - '-host'
      - db
      - '-db'
      - postgres
      - '-u'
      - 'postgres'
      - '-p'
      - password
      # - '-o'
      # - /schema
    volumes:
      - schema:/output

  server:
    image: python:alpine
    volumes:
      - schema:/schema
    command: ['python', '-m', 'http.server', '-d', '/schema']
