# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OspPlugin
                                 A QGIS plugin
 Outil de suivi de projets DDTM13
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-15
        copyright            : (C) 2023 by Camptocamp
        email                : info@camptocamp.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


import configparser
import os


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OspPlugin class from file OspPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rel import RelationPlugin

    return RelationPlugin(iface)


def getPluginName():
    parser = configparser.RawConfigParser()
    parser.read(os.path.join(os.path.dirname(__file__), "metadata.txt"))
    if parser.has_option("general", "name"):
        return parser.get("general", "name")
    # default
    return "OSP"


pluginName = getPluginName()
